"""Add user model

Revision ID: df8c53ad7647
Revises: 
Create Date: 2025-02-25 19:27:52.638016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8c53ad7647'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_entries', sa.Column('triggers', sa.JSON(), nullable=True))
    op.alter_column('diary_entries', 'heart_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('diary_entries', 'hormonal_level',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.create_index(op.f('ix_diary_entries_id'), 'diary_entries', ['id'], unique=False)
    op.add_column('predictions', sa.Column('drift_detected', sa.Boolean(), nullable=True))
    op.alter_column('predictions', 'prediction',
               existing_type=sa.BOOLEAN(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'is_researcher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_researcher', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.alter_column('predictions', 'prediction',
               existing_type=sa.Float(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('predictions', 'drift_detected')
    op.drop_index(op.f('ix_diary_entries_id'), table_name='diary_entries')
    op.alter_column('diary_entries', 'hormonal_level',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('diary_entries', 'heart_rate',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('diary_entries', 'triggers')
    # ### end Alembic commands ###
